[workspace]
git_only = true
release_commits = "^(feat|fix|perf|refactor|build)(!|\\(|:)|^\\w+(\\([^)]*\\))?!:"
git_release_draft = true

[[package]]
name = "tirage"
git_tag_name = "v{{ version }}"

[[package]]
name = "tirage-encode"
release = false

[[package]]
name = "tirage-cli"
release = false
git_tag_name = "tirage-cli-v{{ version }}"
